# Generated by Django 5.0.2 on 2024-06-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
